# Usa la imagen oficial de MySQL 5.7
FROM mysql:5.7

# Establece las variables de entorno para la configuración de MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

# Exponer el puerto 3306 para conexiones externas
EXPOSE 3306